# Generated by Django 3.1 on 2024-08-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('couleur', 'Couleur'), ('taille', 'Taille')], max_length=100),
        ),
    ]
