# Generated by Django 3.1 on 2024-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240806_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Couleur', 'Couleur'), ('Taille', 'Taille')], max_length=100),
        ),
    ]
