# Generated by Django 5.1 on 2024-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewsrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsrating',
            name='review',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
