# Generated by Django 5.1 on 2024-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='userprofile'),
        ),
    ]
